name: Bug 反馈
description: 在使用 Class Widgets 的过程中遇到了 Bug。
title: "[BUG]: "
labels: ["Bug"]
type: "Bug"
body:
  - type: markdown
    attributes:
      value: |
        感谢您进行 Bug 反馈。请起一个能够清晰描述您的问题的标题，便于开发者解决您的问题。
        
        > [!important]
        > 重要：如果要提出 **多个 Bug**，请为每一个 Bug 开一个 **单独** 的 Issue。
        >
        > 如果您不知道如何有效、精准地表述，我们建议您先阅读[《提问的智慧》](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)。

        ### 检查清单

        在反馈此问题之前，请先确认一下事项是否满足：

        1. 我已更新到最新版 ![GitHub Release](https://img.shields.io/github/v/release/RinLit-233-shiroko/Class-Widgets?include_prereleases)，并看过[最新提交](https://github.com/RinLit-233-shiroko/Class-Widgets/commits)。
        2. 我已在 [Issues](https://github.com/RinLit-233-shiroko/Class-Widgets/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过。
        3. 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

  - type: checkboxes
    id: checklist
    attributes:
      label: 确认检查清单
      description: 在反馈此问题之前，请先确认一下事项是否满足：
      options:
        - label: 我已阅读以上清单并确认。
          required: true

  - type: markdown
    attributes:
      value: |
        ## Bug 信息

        描述您遇到的 Bug。您可以附上截图、录屏、堆栈跟踪、日志等材料，便于开发者追踪问题。
        
        > [!WARNING]
        > 若您要上传材料，请等待材料文件上传完成后再发布 Issue。
        >
        > 若显示为 `![Uploading 文件名]()` 即为上传中，请等待链接变动后再提交。

  - type: dropdown
    id: where-happened
    attributes:
      label: 问题发生的位置
      options:
        - 小组件
        - 设置 → 课表预览
        - 设置 → 时间线编辑
        - 设置 → 课程表编辑
        - 设置 → 配置文件
        - 设置 → 帮助
        - 设置 → 插件
        - 设置 → 提醒
        - 设置 → 高级选项
        - 设置 → 关于本产品
        - 错误跟踪窗口
        - 关闭 / 重启
        - 插件
        - 单双周课表
        - 时间线
        - 节点
        - 上下课提醒
        - 插件广场
        - 额外选项
        - 浮窗
        - 其他
      description: 选择问题发生的位置，以便于我们更好发现问题。
    validations:
      required: true

  - type: textarea
    id: excepted
    attributes:
      label: 期望的行为
      description: 详细的描述你期望发生的行为，突出与目前（可能不正确的）行为的不同。（选填）
    validations:
      required: false

  - type: textarea
    id: what-happened
    attributes:
      label: 实际结果
      description: 实际发生的行为，尽量包含如截图、录屏、文本描述等信息，便于开发者追踪问题。
    validations:
      required: true

  - type: textarea
    id: reproduce-steps
    attributes:
      label: 重现步骤
      description: |
        详细描述需要怎么操作才能再次触发这个 Bug，可包含如截图、录屏等附件。
      placeholder: |
        1. 首先……
        2. 然后……
        3. ……
    validations:
      required: true

  - type: textarea
    id: stacktrace
    attributes:
      label: 堆栈跟踪
      description: 如果在遇到这个 Bug 时发生了崩溃（弹出崩溃提示），或者产生了错误日志，请将产生的堆栈跟踪信息粘贴到此处，便于开发者定位 Bug。
      render: shell

  - type: input
    id: app_version
    attributes:
      label: 应用版本
      description: 您当前使用的 Class Widgets 版本号，可以在【设置】->【关于本产品】中查看。
      placeholder: 如：1.2.3
    validations:
      required: true

  - type: input
    id: os_version
    attributes:
      label: 操作系统版本
      description: |
        若您当前使用的操作系统为 Windows，可以运行 `winver.exe` 查看；其他系统的查询方式可上网查阅。
        如果您不能肯定此 Bug 与操作系统无关，请填写此项。
      placeholder: 如：Windows - 10.0.22000.0

  - type: checkboxes
    id: revision
    attributes:
      label: 最后一步
      description: 回顾您的回答
      options:
        - label: 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 Issue 没有按照上述的要求填写，可能会被 **无条件关闭**。
          required: true
